var config = {
    title: "Whitehorse, YT",
    imageName: "image-resize.jpg",
    location: "Vilnius",
    latitude: 54.688860,
    longitude: 25.260100,
    az: 180,
    camera: "ASI224MC",
    computer: "Raspberry Pi 1",
    owner: "Vidma",
    auroraMap: "north",
    overlaySize: 875,
    overlayOffsetLeft: 0,
    overlayOffsetTop: 0,
}
